### ISSUE TITLE
Fix import statements

### ISSUE THREAD

**Issue by sydneychiang** [ctc-uci/bp-women-safety#6]
- [ ] Remove .js from endings in import statements (the image shows what the content should look like)
- [ ] Add semicolons after each import statement

<img width="441" alt="image" src="https://user-images.githubusercontent.com/48849590/157380241-4938cdb8-cd36-4096-92e9-35167edadaa6.png">

**Comment by sydneychiang** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/48849590/157381426-8a77606e-108f-4427-a2dc-d331b974dfad.png">

- [ ] switch the double quotes to single quotes

**Comment by tig-github** [comment]
Fixed formatting - removed import statement extensions and double quotes switched after reformatting with prettier.
